### PR TITLE
SC-3951: Enable Prod assets check and MariaDB check

### PR DESCRIPTION
**Pull request by alexanderM91**
#### Overview

- Ticket: https://spryker.atlassian.net/browse/SC-3951

###### Change log

- Enables Travis's job for prod assets compilation.
- Enables Travis's job for MariaDB check.

### CODE REVIEW

**Comment by dereuromark** [comment]
cannot this be done from suite nonsplit and merged?

**Comment by alexanderM91** [comment]
> cannot this be done from suite nonsplit and merged?

It can be done, but in all cases, it should be adjusted manually.

**Comment by dereuromark** [comment]
yes, but after normal release process! we cannot interfere here.
Auto-release, setting this auto created PR on hold, fixing it up, then removing on hold label.

**Comment by alexanderM91** [comment]
> yes, but after normal release process! we cannot interfere here.
> Auto-release, setting this auto created PR on hold, fixing it up, then removing on hold label.

https://github.com/spryker-shop/suite/pull/572

**Pull request closed without merging**
