### PR TITLE
CI: Add MP tests and build to validation job

### PR DESCRIPTION
**Pull request by gund**
Enable MP tests and build in GA validation job.

_NOTE:_ Merge together with https://github.com/spryker/spryker/pull/8141

### CODE REVIEW

**Comment by dereuromark** [comment]
@gund Whats the status on those?

**Comment by gund** [comment]
@dereuromark I've rebased with master, once CI is green we can merge this.

**Comment by dereuromark** [comment]
You cannot do changes in so many files
This will create heavy merge conflicts from nonsplit side

Instead you should make changes there and make them in a way that they also work for split once merged.
Ideally, it auto detect this based on some indicator like composer (see PHP core how it handles this similarly).

**Comment by gund** [comment]
@dereuromark I changed them because they had not been merged properly - so I needed to update them manually.
I do not really know how otherwise should they be updated because there are always differences in paths that we need to fix manually.

**Pull request merged**
