### PR TITLE
fix webpack config to not kill watch processes

### PR DESCRIPTION
**Pull request by tienbuide**
#### Overview

- Ticket: ?

###### Change log

 - fix webpack compile hook to not kill watch processes

### CODE REVIEW

**Comment by tienbuide** [comment]
ps: it seems like the bug is also present in the [b2c-demo](https://github.com/spryker-shop/b2c-demo-shop/blob/master/frontend/configs/development.js#L187), [b2b-demo](https://github.com/spryker-shop/b2b-demo-shop/blob/master/frontend/configs/development.js#L186) and [b2c-demo-marketplace](https://github.com/spryker-shop/b2c-demo-marketplace/blob/master/frontend/configs/development.js#L187)?

I did not test the diff in the demo/suite but it works like a charm in our setup.

**Comment by dereuromark** [comment]
This must go into our internal nonsplit.
You can take care here?

**Comment by tvaleriy** [comment]
Hi @tienbuide,
thank you for your contribution into Spryker! Due to our development process, I'll need to create an internal ticket for our development team, they will asses it and import the change in our internal repository where they develop. From there it will be released back here as soon as it's ready. And it will be released to other demo shops together with their next public release.

Best,
Spryker Support Team

**Comment by tvaleriy** [comment]
Hi @tienbuide,

this has been released in https://github.com/spryker-shop/suite/pull/981.
Will be integrated into other demo shops later as well. I'm closing this PR.

Thank you for the contribution once again!

Best,
Spryker Support Team

**Pull request closed without merging**
